
# ########################################################
#
# Choose user here
#
# This should be the only change necessary upon switching between our systems
#
# ########################################################

# Uncomment to work on KL's machine
USER=KL
# Uncomment to work on Simon's machine
#USER=SIMON
# ########################################################


# KL's system --------------------------------------------------------------------
ifeq "$(USER)" "KL"
TRILINOS_INSTALL_DIR = ${HOME}/Code/BUILDS/OPT
VIENTO_INSTALL_DIR = ${HOME}/Projects/CFD/BUILDS/OPT
SITE_EXTRA_INCLUDES=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
endif
#----------------------------------------------------------------------------------------

# Simon's system --------------------------------------------------------------------
ifeq "$(USER)" "SIMON"
TRILINOS_INSTALL_DIR = /usr/local/Trilinos/BUILDS/SERIAL-OPT
VIENTO_INSTALL_DIR = ${HOME}/PhDResearch/BUILDS/Viento
SITE_EXTRA_INCLUDES =
endif
#----------------------------------------------------------------------------------------



