#

include ../../Makefile.site
include ../../Makefile.common

#Nothing needed to run the forward code
EXTRA_OBJS =

CLIENT_EXTRA_INCLUDES = -I../../SourceFiles $(SITE_EXTRA_INCLUDES)
CLIENT_EXTRA_LIBS = 

