
include ../Makefile.site
include ../Makefile.common

EXTRA_OBJS = PlayaDenseMatrixMatrixProduct.o

CLIENT_EXTRA_INCLUDES = $(SITE_EXTRA_INCLUDES)
CLIENT_EXTRA_LIBS = 

all: PlayaDenseMatrixMatrixProduct.hpp PlayaDenseMatrixMatrixProduct.cpp main.cpp
	make PlayaDenseMatrixMatrixProduct.o
	make main.exe
